export enum Tools {
  SELECT = "SELECT",
  CREATE_SHAPE = "CREATE_SHAPE",
  CREATE_NEW_COMPONENT_INSTANCE = "CREATE_NEW_COMPONENT_INSTANCE",
  CREATE_NEW_DATA_RESOURCE = "DATA_RESOURCE",
}

export enum MousePosition {
  CANVAS = "CANVAS",
  TOOLBAR = "TOOLBAR",
  LEFT_PANEL = "LEFT_PANEL",
}
