name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

    docker:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          platform:
            - linux/amd64
            - linux/arm64
      needs: build
      steps:
        - name: Prepare
          run: |
            platform=${{ matrix.platform }}
            echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: enesi/editor:latest
            platforms: ${{ matrix.platform }}
